services:

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: evolution_postgres
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution_password
      POSTGRES_DB: evolution
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evolution"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: evolution_redis
    command: redis-server --appendonly yes --requirepass evolution_redis_pass
    restart: always
    volumes:
      - evolution_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "evolution_redis_pass", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  evolution-api:
    image: evoapicloud/evolution-api:v2.3.4
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=SuaSenhaSeguraAqui123
      

      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution_password@postgres:5432/evolution
      

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:evolution_redis_pass@redis:6379/0
      

      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=false
      - DATABASE_SAVE_MESSAGE_UPDATE=false
      - DATABASE_SAVE_DATA_CONTACTS=false
      - DATABASE_SAVE_DATA_CHATS=false
      - LOG_LEVEL=ERROR
      - DEL_INSTANCE=false
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1031796973
    volumes:
      - evolution_store:/evolution/store

volumes:
  evolution_store:
  evolution_postgres_data:
  evolution_redis_data: